### ISSUE TITLE
Update to BioFormats 5.1.4

### ISSUE THREAD

**Issue by sebi06** [CellProfiler/python-bioformats#28]
Hi guys,

when will you update the BioFormats 5.1.4? Or is it still recommended to add the newer libraries manually?

Sebi

**Comment by LeeKamentsky** [comment]
We add the libraries manually ourselves and don't keep pace with releases of bioformats, mostly because we don't allot enough bandwidth to python-bioformats for that kind of thing. You're a heavy user of it, almost part of the team - if you feel comfortable patching it with the latest bioformats_package.jar, running the tests and submitting a pull request, I'll merge it.

**Comment by sebi06** [comment]
Hi Lee,
ok. I was just curious. I will Keep adding the newest BF Version manually because I have to check for the compatibility with our CZI file Format all the time.

Sebi
